// Package mobile exposes the relay proxy for gomobile binding.
package mobile

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"strings"
	"sync"
	"syscall"
	"time"

	"zyrln/relay/core"

)

func init() {
	// Raise the open-file limit so the proxy can handle many concurrent
	// connections without hitting the default Android per-process limit.
	var rl syscall.Rlimit
	if syscall.Getrlimit(syscall.RLIMIT_NOFILE, &rl) == nil {
		rl.Cur = rl.Max
		syscall.Setrlimit(syscall.RLIMIT_NOFILE, &rl)
	}
}

const (
	defaultFrontDomain = "www.google.com"
	defaultTimeout     = 45 * time.Second
	maxLogEntries      = 200
)

// LogEntry is a single log line returned by PollLogs.
type LogEntry struct {
	Level   string // "info" | "error" | "system"
	Message string
}

var (
	mu        sync.Mutex
	server    *http.Server
	listener  net.Listener
	coalescer *core.Coalescer
	lastErr   string

	logMu      sync.Mutex
	logBuf     []LogEntry
	logSeq     int // increments with every new entry
	logReadSeq int // last seq returned to caller
)

func emitLog(level, msg string) {
	logMu.Lock()
	entry := LogEntry{Level: level, Message: msg}
	logBuf = append(logBuf, entry)
	if len(logBuf) > maxLogEntries {
		logBuf = logBuf[1:]
	}
	logSeq++
	logMu.Unlock()
}

// PollLogs returns all log entries added since the last call.
// Returns newline-separated "level\tmessage" strings, or "" if none.
func PollLogs() string {
	logMu.Lock()
	defer logMu.Unlock()
	if logSeq == logReadSeq {
		return ""
	}
	total := len(logBuf)
	if total == 0 {
		logReadSeq = logSeq
		return ""
	}
	missed := logSeq - logReadSeq
	// If the buffer wrapped and we missed more than it holds, return what we have
	if missed > total {
		missed = total
	}
	start := total - missed
	var sb strings.Builder
	for _, e := range logBuf[start:] {
		if sb.Len() > 0 {
			sb.WriteByte('\n')
		}
		sb.WriteString(e.Level)
		sb.WriteByte('\t')
		sb.WriteString(e.Message)
	}
	logReadSeq = logSeq
	return sb.String()
}

// Start starts the HTTPS MITM relay proxy on listenAddr (e.g. "127.0.0.1:8085").
// appScriptURL may be a single URL or a comma-separated list of URLs tried in order.
// caCertPath and caKeyPath must point to an existing CA generated by GenerateCA.
// Returns an error string, or "" on success.
// StartDirect starts the proxy in direct-only mode — no CA or relay config needed.
// Only Google domains (via TLS fragmentation) will work; non-Google HTTPS returns 502.
func StartDirect(listenAddr string) string {
	mu.Lock()
	defer mu.Unlock()

	if server != nil {
		return ""
	}

	core.SetLogFunc(func(level, msg string) { emitLog(level, msg) })
	core.SetDirectEnabled(true)

	client := core.NewHTTPClient(defaultTimeout)
	srv, coal, err := core.StartProxyWithCoalescer(listenAddr, nil, defaultFrontDomain, "", nil, client, defaultTimeout)
	if err != nil {
		lastErr = err.Error()
		emitLog("error", lastErr)
		return lastErr
	}

	ln, err := net.Listen("tcp", listenAddr)
	if err != nil {
		_ = srv.Close()
		lastErr = err.Error()
		emitLog("error", lastErr)
		return lastErr
	}
	go func() { _ = srv.Serve(ln) }()

	srv.ErrorLog = log.New(&logWriter{}, "", 0)

	server = srv
	listener = ln
	coalescer = coal
	lastErr = ""
	emitLog("system", fmt.Sprintf("Direct proxy started on %s", listenAddr))
	return ""
}

func Start(appScriptURL, authKey, listenAddr, caCertPath, caKeyPath string) string {
	mu.Lock()
	defer mu.Unlock()

	if server != nil {
		return ""
	}

	ca, err := core.LoadCA(caCertPath, caKeyPath)
	if err != nil {
		lastErr = fmt.Sprintf("load CA: %s", err)
		emitLog("error", lastErr)
		return lastErr
	}

	core.SetLogFunc(func(level, msg string) { emitLog(level, msg) })

	client := core.NewHTTPClient(defaultTimeout)
	urls := parseURLList(appScriptURL)

	srv, coal, err := core.StartProxyWithCoalescer(listenAddr, urls, defaultFrontDomain, authKey, ca, client, defaultTimeout)
	if err != nil {
		lastErr = err.Error()
		emitLog("error", lastErr)
		return lastErr
	}

	ln, err := net.Listen("tcp", listenAddr)
	if err != nil {
		_ = srv.Close()
		lastErr = err.Error()
		emitLog("error", lastErr)
		return lastErr
	}
	go func() { _ = srv.Serve(ln) }()

	// Redirect server error log to our emitter
	srv.ErrorLog = log.New(&logWriter{}, "", 0)

	server = srv
	listener = ln
	coalescer = coal
	lastErr = ""
	emitLog("system", fmt.Sprintf("Proxy started on %s", listenAddr))
	return ""
}

type logWriter struct{}

func (lw *logWriter) Write(p []byte) (int, error) {
	msg := strings.TrimSpace(string(p))
	if msg != "" {
		emitLog("error", msg)
	}
	return len(p), nil
}

// GetAllLogs returns the entire log buffer including debug entries, for use in
// bug reports. Unlike PollLogs it does not advance the read cursor.
func GetAllLogs() string {
	logMu.Lock()
	defer logMu.Unlock()
	var sb strings.Builder
	for _, e := range logBuf {
		if sb.Len() > 0 {
			sb.WriteByte('\n')
		}
		sb.WriteString(e.Level)
		sb.WriteByte('\t')
		sb.WriteString(e.Message)
	}
	return sb.String()
}

func parseURLList(raw string) []string {
	return core.ParseURLList(raw)
}

// Ping sends a HEAD request through the relay and returns the round-trip time in
// milliseconds as a string (e.g. "142 ms"), or an error message prefixed with "error: ".
// When the proxy is running the existing coalescer (and its warm connection pool) is reused.
func Ping(appScriptURL, authKey string) string {
	mu.Lock()
	coal := coalescer
	mu.Unlock()

	start := time.Now()
	if coal != nil {
		_, err := coal.Submit("HEAD", "https://www.gstatic.com/generate_204", map[string]string{}, nil)
		if err != nil {
			return "error: " + err.Error()
		}
		return fmt.Sprintf("%d ms", time.Since(start).Milliseconds())
	}

	// Proxy not running — use a fresh client
	urls := parseURLList(appScriptURL)
	if len(urls) == 0 {
		return "error: no relay URL configured"
	}
	client := core.NewHTTPClient(defaultTimeout)
	_, err := core.RelayRequestMulti(client, urls, defaultFrontDomain, authKey,
		"HEAD", "https://www.gstatic.com/generate_204",
		map[string]string{}, nil, defaultTimeout)
	if err != nil {
		return "error: " + err.Error()
	}
	return fmt.Sprintf("%d ms", time.Since(start).Milliseconds())
}

// Stop shuts down the relay proxy.
// Uses Close instead of Shutdown to avoid blocking the Android main thread.
func Stop() {
	mu.Lock()
	defer mu.Unlock()
	if coalescer != nil {
		coalescer.Stop()
		coalescer = nil
	}
	if listener != nil {
		_ = listener.Close()
		listener = nil
	}
	if server != nil {
		_ = server.Close()
		server = nil
	}
	emitLog("system", "Proxy stopped")
}

// IsRunning returns true if the proxy is currently running.
func IsRunning() bool {
	mu.Lock()
	defer mu.Unlock()
	return server != nil
}

// LastError returns the last error from Start, or "" if none.
func LastError() string {
	mu.Lock()
	defer mu.Unlock()
	return lastErr
}

// SetCacheDir sets the directory used to persist the remembered direct profile
// across app restarts. Call once at startup with the app's files directory.
func SetCacheDir(dir string) {
	core.SetCacheDir(dir)
}


// SetDomesticBypassEnabled enables routing Iranian domains outside the relay.
func SetDomesticBypassEnabled(enabled bool) {
	core.SetDomesticBypassEnabled(enabled)
}

// IsDomesticBypassEnabled returns whether domestic bypass is on.
func IsDomesticBypassEnabled() bool {
	return core.GetDomesticBypassEnabled()
}

// RefreshDomesticRules reloads the bundled domain list embedded in the app.
func RefreshDomesticRules() {
	core.RefreshDomesticRules()
}

// SetDirectEnabled controls whether Google domains bypass the relay via TLS
// fragmentation. Enabled by default. Safe to call at any time.
func SetDirectEnabled(enabled bool) {
	core.SetDirectEnabled(enabled)
}

// IsDirectEnabled returns the current state of the direct-mode flag.
func IsDirectEnabled() bool {
	return core.GetDirectEnabled()
}

// PingDirect measures a fragmented direct connection to a Google front.
// This exercises the same path live traffic uses: TCP to an open Google domain
// with a fragmented ClientHello to bypass SNI inspection.
// Returns round-trip time as "142 ms" or an error string prefixed with "error: ".
func PingDirect() string {
	start := time.Now()
	conn, ok := core.DialFragment("www.youtube.com:443")
	if !ok {
		return "error: direct connection failed"
	}
	conn.Close()
	return fmt.Sprintf("%d ms", time.Since(start).Milliseconds())
}

// SocketProtector is implemented by the Android VpnService to protect sockets
// from being routed through the VPN tunnel.
type SocketProtector interface {
	Protect(fd int64) bool
}

// SetSocketProtector registers the VPN socket protector so relay HTTP client
// sockets bypass the TUN and don't loop back through the local MITM proxy.
// Call this before Start(). Pass nil to clear.
func SetSocketProtector(p SocketProtector) {
	if p == nil {
		core.SetSocketProtectFunc(nil)
		return
	}
	core.SetSocketProtectFunc(func(fd int) { p.Protect(int64(fd)) })
}

// GenerateCA generates a local CA cert + key at the given paths.
// Returns an error string, or "" on success.
func GenerateCA(certPath, keyPath string) string {
	mu.Lock()
	defer mu.Unlock()
	if err := core.GenerateCA(certPath, keyPath); err != nil {
		return err.Error()
	}
	return ""
}
